### ISSUE TITLE
HAP recording

### ISSUE THREAD

**Issue by stephanschulz** [gameoverhack/ofxHAPAVPlayer#1]
this is not an error report.

i was wondering if you know how to record HAP videos with OF on OSX.
for playback i have used your wonderful ofxThreadedVideo addon and used ofxVideoRecorder to make .mov files. 
thanks for any advice.

**Comment by sebpalluel** [comment]
You can use ofxSyphon and then syphon recorder (http://syphon.v002.info/recorder/) to record in Uncompressed/Hap/DXV at even 60 fps with sound in sync thanks to soundflower. It's by far the best solution to record OF audiovisual works on mac ;).

**Comment by stephanschulz** [comment]
thanks for the tip.

and by sending alt command r i can start and stop the recording process from within OF.

```
void ofApp::keyReleased(int key){

    if(key == 'a'){
        string myScript;

        myScript += "osascript ";
        myScript += "-e 'tell application \"System Events\"' ";
        myScript += "-e 'key code 15 using {command down, option down}' ";
        myScript += "-e 'end tell' ";

        ofLog()<<"myScript "<<myScript;

        system(myScript.c_str());

        //link to key codes
        //http://web.archive.org/web/20100501161453/http://www.classicteck.com/rbarticles/mackeyboard.php
    }
}
```

**Comment by gameoverhack** [comment]
Great tips! Thanks for posting them :)
