### ISSUE TITLE
controlling sound?

### ISSUE THREAD

**Issue by stephanschulz** [gameoverhack/ofxHAPAVPlayer#18]
is there a way to add the ability to set the volume?
I see the setVolume() function is empty. 
maybe you can give me some advice on how to implement this.

thanks so much

**Comment by stephanschulz** [comment]
following the pattern of setSpeed and other function, I created setVolume. 
it seems to work. :)
great add-on.

**Comment by tkayyyyys** [comment]
Hi Stephan,
  I'm trying to do control the volume too.. would you mind sharing your solution setVolume with the community ?! Would be a big help.

Cheers
T

**Comment by stephanschulz** [comment]
hope this helps:
https://github.com/antimodular/ofxHAPAVPlayer

**Comment by tkayyyyys** [comment]
Amazing !! Thank you Stephan!

Do I need to do anything (rebuild?) to get this working with my code?

 I replaced ofxHAPAVPlayer in /addons with your version, then pasted my existing code into the /examples directory. But when I use .setVolume() it doesn't seem to effect the volume and .getVolume() returns 0. Have I missed something ?

**Comment by tkayyyyys** [comment]
My bad. set/get volume works perfectly. Just not if done immediately upon setup. I put a check for .getVolume() in update() and set it to 0 there if it was >= 1. Works great! Hope this helps someone else out too.
