### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by stephanschulz** [gameoverhack/ofxHAPAVPlayer#2]
i am trying to run the addon on OF 0.9.3. with OS X 10.10.5

i had to use project generator to remove some local links from your playerExample, otherwise it had build errors:

```
clang: error: no such file or directory: '/Volumes/GhostDriver/Users/gameover/Code/openFrameworks/addons/ofxHAPAVPlayer/src/ofxHAPAVPlayer.mm'
```

i also went to https://github.com/vidvox/hap-qt-codec/releases/ and installed HapQuickTimeCodec.Mac.v11.pkg . not sure if that was really needed.

it compiles fine now.
i also made sure HapInAVFoundation.framework is inside the .app/Contents/Frameworks folder.

but i get these error when trying to run it:

```
dyld: Library not loaded: @rpath/HapInAVFoundation.framework/Versions/A/HapInAVFoundation
  Referenced from: /Applications/of_v0.9.3_osx_release/addons/ofxHAPAVPlayer/examples/ofxHAPAVPlayerExample/bin/ofxHAPAVPlayerExample.app/Contents/MacOS/ofxHAPAVPlayerExample
  Reason: image not found
```

i should mention that in Xcode "build phases" HapInAVFoundation.framework does not show up in my system, only in your supplied lib folder.

**Comment by stephanschulz** [comment]
ok,i figured it out.

using the project generator removed two lines from the build settings.

i followed point 5 from this readme: https://github.com/Vidvox/hap-in-avfoundation

Switch to the "Build Settings" section of your project's target, locate the "Runpath Search Paths" settings, and make sure that the following paths exist: "@loader_path/../Frameworks" and "@executable_path/../Frameworks".

which means click the little plus sign and copy these phrases in to each added line:
@loader_path/../Frameworks
@executable_path/../Frameworks

**Comment by gameoverhack** [comment]
Hey @stephanschulz I put a note about the run time paths at the bottom of the readme...maybe i should move it up to make it more prominent? Sorry you had to search around to get it going!

**Comment by alptugan** [comment]
> Hey @stephanschulz I put a note about the run time paths at the bottom of the readme...maybe i should move it up to make it more prominent? Sorry you had to search around to get it going!

You should do that! :)
