### ISSUE TITLE
macOS 10.12 + OF 0.10.0

### ISSUE THREAD

**Issue by stephanschulz** [gameoverhack/ofxHAPAVPlayer#20]
I am trying to build the example for OF 0.10.0 but get
`
/Applications/openFrameworks-master/addons/ofxHAPAVPlayer/src/ofxHAPAVPlayerDelegate.h:12:9: 'HapInAVFoundation/HapInAVFoundation.h' file not found
`
 ? not sure why ?
It does not matter which base SDK I select; 10.13 or 10.11

**Comment by stephanschulz** [comment]
I am back at trying to use this great add-on with the newest OF 0.10.0 but get a bunch of compile errors.
Maybe there is a better way to can advantage of the GPU for video play back?
 
<img width="1135" alt="screen shot 2018-11-01 at 3 07 47 pm" src="https://user-images.githubusercontent.com/1054816/47873566-f4db5980-dde7-11e8-985f-368ca65ad3c1.png">

**Comment by mattfelsen** [comment]
I haven't used this addon, but recognize the `string`/`std::string` error. With OF 0.10, the `std` namespace is no longer imported when you `#include "ofMain.h"`, so any code that uses types, functions, etc. from the standard libraries will need to be more explicit.

As a quick & dirty fix, you can add `using namespace std;` to the top of the addon's header. But the more proper way would be to add that at the top of the cpp file instead, and change any declarations in the header from simply `string` to the fully qualified `std::string`. Hopefully that helps. I'm not sure about the last 2 errors though!

**Comment by stephanschulz** [comment]
thanks so much that fixed the string problem.
but unfortunately there are more compile error now for this add-on in OF 0.10 :(

**Comment by stephanschulz** [comment]
new compile errors are 

/Applications/of_v0.10.0_osx_release/addons/ofxHAPAVPlayer/src/ofxHAPAVPlayer.mm:253:25: Use of undeclared identifier 'ofSetPixelStoreiAlignment'

/Applications/of_v0.10.0_osx_release/addons/ofxHAPAVPlayer/src/ofxHAPAVPlayer.mm:323:20: Use of undeclared identifier 'ofIsGLProgrammableRenderer'

<img width="1680" alt="screen shot 2018-11-12 at 9 58 21 am" src="https://user-images.githubusercontent.com/1054816/48355220-86a55b00-e661-11e8-9023-bd2131404d94.png">

**Comment by mattfelsen** [comment]
Looks like those two functions are defined here in `ofGLUtils.h`
https://github.com/openframeworks/openFrameworks/blob/58e47e329d4a2717b5211755a1cb2e65a1a5e1a9/libs/openFrameworks/gl/ofGLUtils.h#L69-L76

I don't see that file being included at the top of  `ofxHAPAVPlayer.h`:
https://github.com/gameoverhack/ofxHAPAVPlayer/blob/master/src/ofxHAPAVPlayer.h#L12-L26

I'm not sure if any of the OF headers that _are_ included pull that in, but you give add `#include "ofGLUtils.h"` and see if that fixes it

**Comment by stephanschulz** [comment]
thanks so much.
adding `#include "ofGLUtils.h"` to ofxHAPAVPlayer.h solved it.
Compiles and runs now nicely in OF 0.10.0
